name: flutterapp
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_treeview: '^1.0.7+1'
  camera: ^0.10.5+9
  google_mlkit_text_recognition: ^0.13.0
  permission_handler: ^11.3.1
  google_ml_kit: ^0.18.0
  video_player: ^2.4.5 
  flick_video_player: ^0.7.0 # Check for newer version or alternative
  cupertino_icons: ^1.0.2
  csslib: ^1.0.0
  # Replaced gallery_picker with an alternative or checked for new version
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/RadixVidSort.mp4
