name: flutterapp
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_treeview: '^1.0.7+1'
  camera: ^0.11.0+2
  google_mlkit_text_recognition: ^0.14.0
  permission_handler: ^11.3.1
  google_ml_kit: ^0.19.0
  video_player: ^2.5.0 
  flick_video_player: ^0.9.0 
  cupertino_icons: ^1.0.2
  csslib: ^1.0.0
  flutter_staggered_grid_view: 0.7.0
  carousel_slider: ^5.0.0
  audioplayers: ^6.0.0
  auto_size_text: ^3.0.0
  collection: ^1.17.1
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  cloud_firestore: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/AL-GO.png"

flutter:
  uses-material-design: true
  assets:
    - assets/RadixVidSort.mp4
    - assets/Learn.png
    - assets/Simulation.png
    - assets/Game.png
    - assets/block-6839.ogg
    - assets/clouds_violet.png
    - assets/card_image.png
    - assets/Card_1st.png
    - assets/Card_2nd.png
    - assets/Slide.png
    - assets/Algo_img.png
    - assets/Algo_img2.png
    - assets/Algo_img3.png
    - assets/bookshelf.png
    - assets/hangman_img.png
    - assets/Stack_img.png
    - assets/Stack_img2.png
    - assets/Tree_img.png
    - assets/Tree_img2.png
    - assets/Tree_img3.png
    - assets/RadixSortTutorial.mp4
    - assets/Insertion_Sort.mp4
    - assets/Depth_First_Search_Tree.mp4
    - assets/Binary_Search_Tree.mp4
    - assets/Breadth_First_Search_Tree.mp4
    - assets/Queue.mp4
    - assets/Merge_Sort.mp4
    - assets/Stacks.mp4
