// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxY24_nATZC9_M_2YzTqllOGMPBtn2Utc',
    appId: '1:777930887360:web:625dfc2954490793421d25',
    messagingSenderId: '777930887360',
    projectId: 'flutterthesis-51a9f',
    authDomain: 'flutterthesis-51a9f.firebaseapp.com',
    storageBucket: 'flutterthesis-51a9f.firebasestorage.app',
    measurementId: 'G-0BHYVDZM9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2vfRdQ8K6BTxDGQmP6IQ10uGy2tVqjoc',
    appId: '1:777930887360:android:927f17eb63cc8d4f421d25',
    messagingSenderId: '777930887360',
    projectId: 'flutterthesis-51a9f',
    storageBucket: 'flutterthesis-51a9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3c8hqdt_VVemEEdnrCwToU1PRxqwQ_68',
    appId: '1:777930887360:ios:6deb27cbf279104d421d25',
    messagingSenderId: '777930887360',
    projectId: 'flutterthesis-51a9f',
    storageBucket: 'flutterthesis-51a9f.firebasestorage.app',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3c8hqdt_VVemEEdnrCwToU1PRxqwQ_68',
    appId: '1:777930887360:ios:6deb27cbf279104d421d25',
    messagingSenderId: '777930887360',
    projectId: 'flutterthesis-51a9f',
    storageBucket: 'flutterthesis-51a9f.firebasestorage.app',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxY24_nATZC9_M_2YzTqllOGMPBtn2Utc',
    appId: '1:777930887360:web:bad08b4d9c89da71421d25',
    messagingSenderId: '777930887360',
    projectId: 'flutterthesis-51a9f',
    authDomain: 'flutterthesis-51a9f.firebaseapp.com',
    storageBucket: 'flutterthesis-51a9f.firebasestorage.app',
    measurementId: 'G-KFYQF02YD6',
  );
}
